title: LBlue's Thought Bubble
description: > # this means to ignore newlines until "baseurl:"
  This is a time machine for me<br>
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://LBluu.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'LBlue'
  last_name: ''
  cv: ''
  avatar: '/images/avatar.jpeg'
  github_username:  LBluu  
  email: lblueblue@buaa.edu.cn
  vk_id: 
  telegram_name: 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


