title: "LBlue-Thought-Bubble"
tagline: "study between meal and sleep!"
description: "This is a time machine for me."
github_username: LBluu
baseurl: ""
url: "https://LBluu.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
