title: "LBlue-Thought-Bubble"
email: lblueblue@buaa.edu.cn
# tagline: "study between meal and sleep!"
description: >-
  This is a time machine for me.
github_username: LBluu
baseurl: "/blog"
url: "https://LBluu.github.io"

plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - about.md
  - a-third-page.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]

